import proc from 'child_process'

proc.exec('git status -z', (err, out) => {
  out = out ? out.toString().trim() : ''
  if (err || out.length > 0) {
    console.error('Please commit all changes generated by building')
    process.exit(1)
  }
})
